version: '3.7'
services:
    php-fpm:
        build:
            context:    .
            dockerfile: .docker/php-fpm/Dockerfile
        expose:
            - "80"
            - "8080"
        depends_on:
            - mariadb
        volumes:
            - ${PWD}/:/opt/app
            - ${PWD}/.docker
        command: php-fpm
        ports:
            - "80:80"
            - "8080:8080"
        environment:
            - COMPOSER_MEORY_LIMIT=-1
            - COMPOSER_ALLOW_XDEBUG=1
            - COMPOSER_DISABLE_XDEBUG_WARN=1

    mariadb:
        build:
            context:    .
            dockerfile: .docker/mysql/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: DockerPluginSkeleton
            MYSQL_DATABASE:      DockerPluginSkeleton
            MYSQL_USER:          DockerPluginSkeleton
            MYSQL_PASSWORD:      DockerPluginSkeleton
        volumes:
            - ${PWD}/.docker/mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"

    hub:
        image: selenium/hub:3.11.0
        ports:
            - 4444:4444
        links:
            - php-fpm
    chrome:
#        image: selenium/node-chrome:3.11.0
        #  You can also use this image and open the  container port to one of your host port to be able to use a VNC viewer
        image: selenium/node-chrome-debug:3.11.0
        depends_on:
            - hub
        links:
            - php-fpm
        environment:
            - HUB_HOST=hub
            - HUB_PORT=4444
        # ports:
        #     - 5900:5900
